<?php
/**
 * ============================================================================
 * BACKUP & RESTORE DASHBOARD
 * ============================================================================
 */

require_once '../config/config.php';
require_once '../includes/functions.php';

require_role('admin');

$page_title = "Backup & Restore";
require_once '../includes/header.php';
?>

<div class="page-header">
    <h2 class="page-title">
        <span class="page-icon">💾</span>
        Backup & Recovery
    </h2>
</div>

<div class="row">
    <!-- EXCEL BACKUP -->
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-header">
                <h3 class="card-title">📊 Excel Data Backup</h3>
            </div>
            <div class="card-body text-center" style="padding: 30px;">
                <div style="font-size: 40px; margin-bottom: 20px;">📑</div>
                <h4 style="margin-bottom: 10px;">Export to Excel</h4>
                <p class="text-muted" style="font-size: 13px; margin-bottom: 25px;">
                    Download all your data (Products, Customers, Invoices, etc.) in a single Excel file with multiple sheets.
                </p>
                <a href="export_excel.php" class="btn btn-primary btn-block">
                    <span class="btn-icon">⬇️</span> Download Excel
                </a>
            </div>
        </div>
    </div>

    <!-- SQL BACKUP -->
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-header">
                <h3 class="card-title">🗄️ Database Backup</h3>
            </div>
            <div class="card-body text-center" style="padding: 30px;">
                <div style="font-size: 40px; margin-bottom: 20px;">💾</div>
                <h4 style="margin-bottom: 10px;">Export SQL</h4>
                <p class="text-muted" style="font-size: 13px; margin-bottom: 25px;">
                    Download a raw SQL file of your entire database. Use this for full system recovery or migration.
                </p>
                <a href="export_sql.php" class="btn btn-warning btn-block" style="color:white;">
                    <span class="btn-icon">⬇️</span> Download SQL
                </a>
            </div>
        </div>
    </div>

    <!-- RESTORE -->
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-header">
                <h3 class="card-title">♻️ System Recovery</h3>
            </div>
            <div class="card-body text-center" style="padding: 30px;">
                <div style="font-size: 40px; margin-bottom: 20px;">🔄</div>
                <h4 style="margin-bottom: 10px;">Import / Restore</h4>
                <p class="text-muted" style="font-size: 13px; margin-bottom: 15px;">
                    Upload a .sql file to restore your database.
                    <br><strong class="text-danger">WARNING: This will overwrite existing data!</strong>
                </p>
                
                <form action="import_sql.php" method="POST" enctype="multipart/form-data" id="restoreForm">
                    <div style="margin-bottom: 15px;">
                        <input type="file" name="backup_file" accept=".sql" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-danger btn-block" onclick="return confirm('Are you sure? This will delete all current data and replace it with the backup. This cannot be undone!')">
                        <span class="btn-icon">⬆️</span> Restore Database
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" style="margin-top: 30px;">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">ℹ️ Backup Information</h3>
            </div>
            <div class="card-body">
                <ul style="color: #64748b; font-size: 14px; line-height: 1.8;">
                    <li><strong>Excel Backup:</strong> Useful for viewing your data, reporting, or manual analysis. Formatted for readability.</li>
                    <li><strong>SQL Backup:</strong> The standard format for database backups. Contains structure and data. Essential for disaster recovery.</li>
                    <li><strong>Recovery:</strong> Only accepts <code>.sql</code> files generated by this system or standard mysqldump. Ensure you have a backup of the current state before restoring an old one.</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php require_once '../includes/footer.php'; ?>
